### PR TITLE
Permissions update for Android 6.0+

### PR DESCRIPTION
**Pull request by poocart**
Added READ_EXTERNAL_STORAGE permission dialog for Andorid 6.0+ users.

### CODE REVIEW

**Comment by BugsBunnyBR** [comment]
+1

**Comment by Findiglay** [comment]
+1

**Comment by Nicolazinho** [comment]
+1

**Comment by vicentebalderas** [comment]
+1

**Comment by yzargari** [comment]
+1

**Comment by kaplanmaxe** [comment]
+1

**Comment by Seongsoo-Kim** [comment]
+1 it's nice solution.

**Comment by SanHoser** [comment]
When are you going to merge?

**Comment by dustinwag** [comment]
+1

**Comment by Seongsoo-Kim** [comment]
@SanHoser  Look at this code and change your MultiChooser.java
https://github.com/wymsee/cordova-imagePicker/pull/136/commits/20dbe9d027da990a8b7e514aa4b5262181beadc3

**Comment by SanHoser** [comment]
@Seongsoo-Kim Yes, I've cherry picked the class in order to unblock myself.   However, I'd prefer pulling the code from the main repo to keep up with updates and fixes.

**Comment by aabde** [comment]
+1

**Comment by Rakonda** [comment]
+1

**Comment by Findiglay** [comment]
Any idea when this might be going in? It's quite an essential update.

**Comment by mklilley** [comment]
Agreed.  I have test users of my app who are reporting crashses on first use of the imagePicker.  Seems like this pull request will provide a big fix no?

**Comment by EralpB** [comment]
This is so important.

**Comment by mklilley** [comment]
I just tried the suggestion by @kumquat0601 i.e. I just replaced my MultiImageChooserActivity.java with the one here 20dbe9d027da990a8b7e514aa4b5262181beadc3 .  My friend who is using Nexus 5 reported that the imagePicker didn't crash at first this time, but there were no images to select. Then when he loaded the app a second time the whole thing immedtely crashed. Only after he gave permission to take a photo did the imagePicker then work ok. Has anyone else tried this kind of approach and did it work for you?   Thanks

**Comment by kumquat0601** [comment]
@mklilley Oh, I didn't test Nexus devices. I only tested iPhone 5, galaxy series. Other Nexus users need to refer your comments.

**Comment by gagaXD** [comment]
Any idea when this is going to be merged ?

**Comment by kbondarev** [comment]
+1
Please merge this

**Comment by rpayanm** [comment]
Why so much delay in merge this important issue?

**Comment by badpenguin** [comment]
How can i install this with "cordova plugin add" ? The plugin is crashing for me too :-/

**Comment by wparad** [comment]
@badpenguin Run this:
`cordova plugin add https://github.com/Findiglay/cordova-imagePicker.git#20dbe9d0 --save`

**Comment by fenglu09** [comment]
+1

**Comment by nomanbiniqbal** [comment]
+1

**Comment by royipressburger** [comment]
Any news regarding this?

**Comment by wmenegali** [comment]
I've changed the files on my own and it worked out great! What's happening with the merge?

**Comment by alexislg2** [comment]
Works great thanks. Waiting for the merge!

**Comment by amostech** [comment]
+1 This shall be included in the main stream ASAP!

**Comment by sarantist** [comment]
Is there a reason for not merging?

**Comment by amostech** [comment]
@DMcNamara @gianpaj @sdushay

This sounds like an important merge, we are all using the new permission. Do you guys have plans to merge this into the main stream?

**Comment by royipressburger** [comment]
https://github.com/Telerik-Verified-Plugins/ImagePicker

This is a working replacement is someone is looking

**Comment by bmwertman** [comment]
Is this going to be merged? I just had the same permission error from a user running Android N on a Google Pixel device.

**Comment by luiseduardobrito** [comment]
+1

**Comment by Spriz** [comment]
Hi there! I took the liberty of merging your changes to my fork at https://github.com/Spriz/cordova-imagePicker :-)

**Review by gifthlong — APPROVED** [review]

**Comment by sdushay** [comment]
Hey @poocart can we close this?

**Comment by poocart** [comment]
Closed.

**Pull request closed without merging**
